apiVersion: v1
kind: ConfigMap
metadata:
  name: cnpg-console-config
  labels:
    {{- include "cnpg-console.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
